module.exports = {
  DocsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Tài liệu',
    },
    {
      type: 'category',
      label: 'Bắt đầu',
      collapsible: true,
      link: { type: 'doc', id: 'batdau/overview' },
      items: [
        {
          type: 'category',
          label: 'Các bước đầu tiên',
          items: [
            'batdau/cac-buoc-dau-tien/chin-buoc',
            'batdau/cac-buoc-dau-tien/thiet-lap',
            'batdau/cac-buoc-dau-tien/cai-dat',
          ],
        },
        {
          type: 'category',
          label: 'Hỏi đáp',
          items: ['batdau/hoi-dap/who', 'batdau/hoi-dap/where'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Quản lý Bảng điều khiển',
      collapsible: true,
      link: { type: 'doc', id: 'bang-dieu-khien/overview' },
      items: [
        {
          type: 'category',
          label: 'Đơn hàng',
          collapsible: true,
          link: { type: 'doc', id: 'directory-sync/providers/index' },
          items: ['directory-sync/providers/azure'],
        },
        {
          type: 'category',
          label: 'Sản phẩm',
          collapsible: true,
          link: { type: 'doc', id: 'directory-sync/providers/index' },
          items: ['directory-sync/providers/azure'],
        },
        {
          type: 'category',
          label: 'Lịch',
          collapsible: true,
          link: { type: 'doc', id: 'directory-sync/providers/index' },
          items: ['directory-sync/providers/azure'],
        },
        {
          type: 'category',
          label: 'Tăng doanh số',
          collapsible: true,
          link: { type: 'doc', id: 'directory-sync/providers/index' },
          items: ['directory-sync/providers/azure'],
        },
        {
          type: 'category',
          label: 'Phân tích',
          collapsible: true,
          link: { type: 'doc', id: 'directory-sync/providers/index' },
          items: ['directory-sync/providers/azure'],
        },
        {
          type: 'category',
          label: 'Cài đặt chung',
          collapsible: true,
          link: { type: 'doc', id: 'directory-sync/providers/index' },
          items: ['directory-sync/providers/jumpcloud'],
        },
        {
          type: 'category',
          label: 'Phương thức giao hàng',
          collapsible: true,
          link: { type: 'doc', id: 'directory-sync/providers/index' },
          items: ['directory-sync/providers/jumpcloud'],
        },
        {
          type: 'category',
          label: 'Thanh toán',
          collapsible: true,
          link: { type: 'doc', id: 'directory-sync/providers/index' },
          items: ['directory-sync/providers/jumpcloud'],
        },
        {
          type: 'category',
          label: 'Hiển thị',
          collapsible: true,
          link: { type: 'doc', id: 'directory-sync/providers/index' },
          items: ['directory-sync/providers/jumpcloud'],
        },
        {
          type: 'category',
          label: 'Gói dịch vụ',
          collapsible: true,
          link: { type: 'doc', id: 'directory-sync/providers/index' },
          items: ['directory-sync/providers/azure'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Phát triển kinh doanh của bạn.',
      collapsible: true,
      link: { type: 'doc', id: 'retraced/overview' },
      items: [
        {
          type: 'category',
          label: 'Kết nối trang web của bạn.',
          link: { type: 'doc', id: 'retraced/getting-started/retraced-basics' },
          items: [
            'retraced/getting-started/embedded-viewer',
            'retraced/getting-started/first-audit-event',
            'retraced/getting-started/renaming-properties',
            'retraced/getting-started/searching-for-events',
            'retraced/getting-started/time-synchronization',
          ],
        },
        {
          type: 'category',
          label: 'Khuyến mại',
          link: { type: 'doc', id: 'retraced/self-host/index' },
          items: [
            'retraced/self-host/local',
            'retraced/self-host/docker',
            'retraced/self-host/digitalocean',
            'retraced/self-host/aws',
            'retraced/self-host/kubernetes',
            'retraced/self-host/skaffold',
          ],
        },
        {
          type: 'category',
          label: 'Phân tích',
          link: { type: 'doc', id: 'retraced/self-host/index' },
          items: [
            'retraced/self-host/local',
            'retraced/self-host/docker',
            'retraced/self-host/digitalocean',
            'retraced/self-host/aws',
            'retraced/self-host/kubernetes',
            'retraced/self-host/skaffold',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Sắp ra mắt',
      collapsible: true,
      link: { type: 'doc', id: 'admin-portal/overview' },
      items: ['admin-portal/enterprise-sso', 'admin-portal/directory-sync'],
    },
  ],
};
